logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      maximum-pool-size: 3
    username: crescer
    password: crescer
    url: jdbc:oracle:thin:@10.99.220.86:1521:ORCL